"""
Emits a portable, human-readable .sql file (CREATE TABLE + INSERT) reconstructed from
information_schema, with geometry written as ST_GeomFromText(..., 0).

Scope: the small metadata tables only. Every row of each table is fetched into memory and
concatenated into a single multi-row INSERT, so pointing this at meo_exposure_samples
(~1.57 billion rows) will exhaust RAM. Use db_robust_export.ps1 (parallel pg_dump) for a real
backup; this exists for schema portability and hand-inspectable snapshots.

Table and column names are interpolated into the SQL rather than parameterised. That is safe
here because they come from information_schema (not user input), but do not repurpose these
query strings for externally supplied identifiers.
"""

import psycopg2
import os

DB_CONFIG = {
    "host": "localhost",
    "port": 5432,
    "database": "city_data",
    "user": "admin",
    "password": "password"
}

SQL_DIR = "sql"
OUTPUT_FILE = os.path.join(SQL_DIR, "city_data_dump.sql")

def export_to_sql():
    if not os.path.exists(SQL_DIR):
        os.makedirs(SQL_DIR)
        print(f"Created directory: {SQL_DIR}")

    conn = psycopg2.connect(**DB_CONFIG)
    cur = conn.cursor()

    # Get all tables in the public schema
    cur.execute("SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_type = 'BASE TABLE'")
    tables = [row[0] for row in cur.fetchall() if row[0] != 'spatial_ref_sys']

    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write("-- Database Export\n")
        f.write("-- Generated by ShadowAware Export Script\n\n")
        f.write("CREATE EXTENSION IF NOT EXISTS postgis;\n\n")

        for table in tables:
            print(f"Dumping table: {table}...")
            f.write(f"-- Table: {table}\n")
            
            # 1. Get CREATE TABLE statement (Simplified version)
            cur.execute(f"""
                SELECT column_name, data_type, udt_name, is_nullable, column_default
                FROM information_schema.columns 
                WHERE table_name = '{table}' AND table_schema = 'public'
                ORDER BY ordinal_position
            """)
            cols_info = cur.fetchall()
            
            f.write(f"CREATE TABLE IF NOT EXISTS {table} (\n")
            col_defs = []
            col_names = []
            col_types = []
            
            for col, dtype, udt, nullable, default in cols_info:
                col_names.append(col)
                col_types.append(udt)
                
                type_str = dtype
                if udt == 'geometry':
                    # Find geometry type and srid
                    cur.execute(f"SELECT type, srid FROM geometry_columns WHERE f_table_name = '{table}' AND f_geometry_column = '{col}'")
                    geom_info = cur.fetchone()
                    if geom_info:
                        type_str = f"GEOMETRY({geom_info[0]}, {geom_info[1]})"
                    else:
                        type_str = "GEOMETRY"
                elif dtype == 'USER-DEFINED':
                    type_str = udt
                
                null_str = "NOT NULL" if nullable == 'NO' else ""
                def_str = f"DEFAULT {default}" if default else ""
                col_defs.append(f"    {col} {type_str} {null_str} {def_str}".strip())
            
            f.write(",\n".join(col_defs))
            f.write("\n);\n\n")

            # 2. Get Data
            select_parts = []
            for col, dtype, udt, nullable, default in cols_info:
                if udt == 'geometry':
                    select_parts.append(f"ST_AsText({col})")
                else:
                    select_parts.append(col)
            
            cur.execute(f"SELECT {', '.join(select_parts)} FROM {table}")
            rows = cur.fetchall()
            
            if rows:
                f.write(f"INSERT INTO {table} ({', '.join(col_names)}) VALUES\n")
                insert_rows = []
                for row in rows:
                    values = []
                    for i, val in enumerate(row):
                        if val is None:
                            values.append("NULL")
                        elif col_types[i] == 'geometry':
                            values.append(f"ST_GeomFromText('{val}', 0)") # Assuming SRID 0 based on previous context
                        elif isinstance(val, bool):
                            values.append("TRUE" if val else "FALSE")
                        elif isinstance(val, (int, float)):
                            values.append(str(val))
                        else:
                            # Handle strings/dates/uuids
                            clean_val = str(val).replace("'", "''")
                            values.append(f"'{clean_val}'")
                    insert_rows.append(f"({', '.join(values)})")
                
                f.write(",\n".join(insert_rows))
                f.write(";\n\n")

    conn.close()
    print(f"\nSQL export complete! File saved to: {OUTPUT_FILE}")

if __name__ == "__main__":
    export_to_sql()
